id: A321E2E3B
title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long Life
  of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:31:26.643093
  last_modified_at: 2022-03-01 00:31:26.643097
