id: A321E2E3B
title: Prayer for the Long Life of Khyenrab Chökyi Özer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:31:26.639001
  last_modified_at: 2022-03-01 00:31:26.639008
